<script setup lang="ts">
const route = useRoute();
const name = computed(() => String(route.params.name));

/** Keyed by the file being read, and it has to be.
 *
 * Without a key Nuxt derives one from the call site, which is the same for
 * every /plik/* route - so all of them shared one entry. The page component is
 * remounted on a param change, but under Suspense the outgoing page is still
 * mounted while the incoming one runs setup, so `nuxtApp._asyncData[key]` is
 * already there with status "success" and the handler is skipped outright.
 * Clicking „Polityka prywatności" in the footer while on „Regulamin" changed
 * the url and left the regulamin on the screen, tab title and all. */
const { data: file } = await useAsyncData(
  () => `content:${name.value}`,
  () => queryCollection("content").path(`/${name.value}`).first(),
);

// Getters, so the tab title follows the document rather than being captured
// once - the same staleness as above, one layer up.
useSeoMeta({
  title: () => file.value?.title,
  description: () => file.value?.description,
});

// The white sheet on a grey band that /o-nas and /pomoc stand on, asked for by
// the owner: „use the gray layout for contrast”. This page used to draw its own
// sheet on the white page, where only a 1px shadow told the two apart. 860
// rather than the layout's 1200 keeps the text as wide as it was on that sheet,
// about 74 characters a line; at 1200 the regulamin's lines average 100.
definePageMeta({
  layout: "gray",
  fullWidth: true,
  maxWidth: 860,
});
</script>

<template>
  <div class="content-styles">
    <ContentRenderer v-if="file" :value="file" />
    <div v-else class="text-center text-h5 text-medium-emphasis">
      Nie znaleziono strony
    </div>
  </div>
</template>

<style>
.content-styles {
  font-family: Roboto, sans-serif;
  color: rgba(0, 0, 0, 0.87);
  line-height: 1.6;
}

.content-styles h1 {
  font-size: 2.25rem;
  font-weight: 500;
  margin-bottom: 32px;
  line-height: 1.2;
}

.content-styles h2 {
  font-size: 1.75rem;
  font-weight: 500;
  margin-top: 48px;
  margin-bottom: 24px;
  line-height: 1.3;
}

.content-styles h3 {
  font-size: 1.35rem;
  font-weight: 500;
  margin-top: 32px;
  margin-bottom: 16px;
}

.content-styles p {
  font-size: 1.05rem;
  margin-bottom: 20px;
}

.content-styles ul,
.content-styles ol {
  margin-bottom: 20px;
  padding-left: 28px;
  font-size: 1.05rem;
}

.content-styles li {
  margin-bottom: 8px;
}

/* Hide the anchor links generated by Nuxt Content on headings */
.content-styles h1 a,
.content-styles h2 a,
.content-styles h3 a,
.content-styles h4 a,
.content-styles h5 a,
.content-styles h6 a {
  text-decoration: none !important;
  color: inherit !important;
  pointer-events: none; /* Prevent clicking on anchors */
}

/* Hide hashtag or other icons */
.content-styles h1 a .icon,
.content-styles h2 a .icon,
.content-styles h3 a .icon,
.content-styles h1 a::before,
.content-styles h2 a::before,
.content-styles h3 a::before,
.content-styles h1 a::after,
.content-styles h2 a::after,
.content-styles h3 a::after {
  display: none !important;
  content: none !important;
}

.content-styles strong {
  font-weight: 600;
}

/* Ink, not the brand's sage fill: #a8c79f is 1.85:1 on the white sheet, so
   the e-mail address and „Polityka Prywatności” were the faintest words on a
   page asked to have more contrast. ink-sage is the same green at 6.43:1. */
.content-styles a:not(h1 a):not(h2 a):not(h3 a):not(h4 a):not(h5 a):not(h6 a) {
  color: rgb(var(--v-theme-ink-sage));
  text-decoration: none;
  font-weight: 500;
  transition: all 0.2s ease;
}

.content-styles
  a:not(h1 a):not(h2 a):not(h3 a):not(h4 a):not(h5 a):not(h6 a):hover {
  text-decoration: underline;
  opacity: 0.8;
}
</style>
