<script setup lang="ts">
const route = useRoute();
const name = route.params.name as string;
const { data: file } = await useAsyncData(() =>
  queryCollection("content")
    .path("/" + name)
    .first(),
);

useSeoMeta({
  title: file.value?.title,
  description: file.value?.description,
});
</script>

<template>
  <v-container max-width="900" class="py-12">
    <v-sheet elevation="1" rounded="xl" class="pa-8 pa-md-12 content-styles">
      <ContentRenderer v-if="file" :value="file" />
      <div v-else class="text-center text-h5 text-medium-emphasis">
        Nie znaleziono strony
      </div>
    </v-sheet>
  </v-container>
</template>

<style>
.content-styles {
  font-family: Roboto, sans-serif;
  color: rgba(0, 0, 0, 0.87);
  line-height: 1.6;
}

.content-styles h1 {
  font-size: 2.25rem;
  font-weight: 500;
  margin-bottom: 32px;
  line-height: 1.2;
}

.content-styles h2 {
  font-size: 1.75rem;
  font-weight: 500;
  margin-top: 48px;
  margin-bottom: 24px;
  line-height: 1.3;
}

.content-styles h3 {
  font-size: 1.35rem;
  font-weight: 500;
  margin-top: 32px;
  margin-bottom: 16px;
}

.content-styles p {
  font-size: 1.05rem;
  margin-bottom: 20px;
}

.content-styles ul,
.content-styles ol {
  margin-bottom: 20px;
  padding-left: 28px;
  font-size: 1.05rem;
}

.content-styles li {
  margin-bottom: 8px;
}

/* Hide the anchor links generated by Nuxt Content on headings */
.content-styles h1 a,
.content-styles h2 a,
.content-styles h3 a,
.content-styles h4 a,
.content-styles h5 a,
.content-styles h6 a {
  text-decoration: none !important;
  color: inherit !important;
  pointer-events: none; /* Prevent clicking on anchors */
}

/* Hide hashtag or other icons */
.content-styles h1 a .icon,
.content-styles h2 a .icon,
.content-styles h3 a .icon,
.content-styles h1 a::before,
.content-styles h2 a::before,
.content-styles h3 a::before,
.content-styles h1 a::after,
.content-styles h2 a::after,
.content-styles h3 a::after {
  display: none !important;
  content: none !important;
}

.content-styles strong {
  font-weight: 600;
}

.content-styles a:not(h1 a):not(h2 a):not(h3 a):not(h4 a):not(h5 a):not(h6 a) {
  color: #a8c79f;
  text-decoration: none;
  font-weight: 500;
  transition: all 0.2s ease;
}

.content-styles
  a:not(h1 a):not(h2 a):not(h3 a):not(h4 a):not(h5 a):not(h6 a):hover {
  text-decoration: underline;
  opacity: 0.8;
}
</style>
