/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/Home.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    List: typeof import('./components/List.vue')['default']
    ListView: typeof import('./components/ListView.vue')['default']
    PartyChart: typeof import('./components/PartyChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
