/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(zobacz)': RouteRecordInfo<'/(zobacz)', '/', Record<never, never>, Record<never, never>>,
    '/(zobacz)/graf': RouteRecordInfo<'/(zobacz)/graf', '/graf', Record<never, never>, Record<never, never>>,
    '/(zobacz)/lista': RouteRecordInfo<'/(zobacz)/lista', '/lista', Record<never, never>, Record<never, never>>,
    '/(zobacz)/pomoc': RouteRecordInfo<'/(zobacz)/pomoc', '/pomoc', Record<never, never>, Record<never, never>>,
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/entity/[destination]/[id]': RouteRecordInfo<'/entity/[destination]/[id]', '/entity/:destination/:id', { destination: ParamValue<true>, id: ParamValue<true> }, { destination: ParamValue<false>, id: ParamValue<false> }>,
    '/entity/[...path]': RouteRecordInfo<'/entity/[...path]', '/entity/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/profil': RouteRecordInfo<'/profil', '/profil', Record<never, never>, Record<never, never>>,
    '/zrodla': RouteRecordInfo<'/zrodla', '/zrodla', Record<never, never>, Record<never, never>>,
  }
}
